"""create minerals table

Revision ID: 2a6912b0647d
Revises: 
Create Date: 2026-03-26 16:20:55.080881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6912b0647d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minerals',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('mineral_name', sa.String(), nullable=False),
    sa.Column('region_province', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('primary_use_industry', sa.String(), nullable=False),
    sa.Column('applications', sa.Text(), nullable=False),
    sa.Column('mining_status', sa.Enum('Active', 'Inactive', 'Artisanal', name='miningstatus'), nullable=False),
    sa.Column('year_recorded', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('data_quality_flag', sa.Enum('VERIFIED', 'UNVERIFIED', 'FIELD_ESTIMATE', 'CONFLICTING_SOURCE', 'AWAITING_REVIEW', name='dataqualityflag'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minerals')
    # ### end Alembic commands ###
